export interface PlayerStats {
  level: number;
  xp: number;
  currentXp: number;
  nextLevelXp: number;
  hp: number;
  maxHp: number;
  stamina: number;
  maxStamina: number;
  skillPoints: number;
  totalSkillPointsEarned: number;
  kills: number;
  killsByType: Record<string, number>;
  deaths: number;
  sectorsCompleted: number;
  scrap: number;
  totalScrapCollected: number;
  totalBulletsFired: number;
  totalBulletsHit: number;
  totalThrowablesThrown: number;
  totalDamageDealt: number;
  totalDamageTaken: number;
  totalDistanceTraveled: number;
  chestsOpened: number;
  bigChestsOpened: number;
  collectiblesDiscovered: string[];
  viewedCollectibles?: string[];
  cluesFound: string[];
  discoveredPOIs: string[];
  seenEnemies: string[];
  seenBosses: string[];
  prologueSeen?: boolean;
  speed: number;
  rescuedFamilyIds: number[];
  familyFoundCount: number;
  mostUsedWeapon: string;
  deathsByEnemyType: Record<string, number>;
  incomingDamageBreakdown: Record<string, Record<string, number>>;
  outgoingDamageBreakdown: Record<string, number>;
}
