import { WeaponType } from '../content/weapons';
import { PlayerStats } from '../entities/player/PlayerTypes';
import { GameSettings, WeatherType, EnvironmentOverride } from '../core/engine/EngineTypes';
import { SectorStats, SectorState } from './StateTypes';

export interface GameCanvasProps {
  stats: PlayerStats;
  loadout: {
    primary: WeaponType;
    secondary: WeaponType;
    throwable: WeaponType;
    special: WeaponType;
  };
  weaponLevels: Partial<Record<WeaponType, number>>;
  currentSector: number;
  deadBossIndices: number[];
  rescuedFamilyIndices: number[];
  debugMode?: boolean;
  isGameRunning: boolean;
  isPaused: boolean;
  onDie: (stats: SectorStats, killer: string) => void;
  onSectorEnded: (stats: SectorStats) => void;
  onPauseToggle: (val: boolean) => void;
  onOpenMap: () => void;
  triggerEndSector: boolean;
  familyAlreadyRescued: boolean;
  bossPermanentlyDefeated: boolean;
  onSectorLoaded: () => void;
  startAtCheckpoint: boolean;
  onCheckpointReached: () => void;
  teleportTarget: { x: number, z: number, timestamp: number } | null;
  onCollectibleDiscovered: (id: string) => void;
  onClueDiscovered: (clue: any) => void;
  onPOIdiscovered: (poi: any) => void;
  onEnemyDiscovered?: (type: number) => void;
  onBossDiscovered?: (id: number) => void;
  onBossKilled?: (id: number) => void;
  onFamilyRescued?: (id: number) => void;
  isCollectibleOpen: boolean;
  onCollectibleClose: () => void;
  onDialogueStateChange: (active: boolean) => void;
  onDeathStateChange: (active: boolean) => void;
  onBossIntroStateChange: (active: boolean) => void;
  onUpdateLoadout?: (loadout: any, levels: any) => void;
  onEnvironmentOverrideChange?: (overrides: EnvironmentOverride, weather: WeatherType) => void;
  environmentOverrides?: Record<number, EnvironmentOverride>;
  onInteractionStateChange?: (type: string | null) => void;
  isMobileDevice?: boolean;
  disableInput?: boolean;
  isWarmup?: boolean;
  weather: WeatherType;
  settings: GameSettings;
  currentSectorData?: any;
  sectorState?: SectorState;
}
