import { SessionStats } from './SessionStats';
import { WeatherType, EnvironmentOverride } from '../core/engine/EnvironmentalTypes';
import { GameState } from './StateTypes';

export interface GameCanvasProps {
  gameState: GameState;
  isGameRunning: boolean;
  isPaused: boolean;
  onDie: (sessionStats: SessionStats, killer: string) => void;
  onSectorEnded: (sessionStats: SessionStats) => void;
  onPauseToggle: (pause: boolean) => void;
  onOpenMap: () => void;
  triggerEndSector: boolean;
  familyAlreadyRescued: boolean;
  bossPermanentlyDefeated: boolean;
  onSectorLoaded: () => void;
  startAtCheckpoint: boolean;
  onCheckpointReached: () => void;
  teleportTarget: { x: number, z: number, timestamp: number } | null;
  onCollectibleDiscovered: (id: string) => void;
  onClueDiscovered: (clue: any) => void;
  onPOIdiscovered: (poi: any) => void;
  onEnemyDiscovered?: (type: number) => void;
  onBossDiscovered?: (id: number) => void;
  onBossKilled?: (id: number) => void;
  onFamilyRescued?: (id: number) => void;
  onPerkDiscovered?: (id: number) => void;
  isCollectibleOpen: boolean;
  onCollectibleClose: () => void;
  onDialogueStateChange: (active: boolean) => void;
  onDeathStateChange: (active: boolean) => void;
  onBossIntroStateChange: (active: boolean) => void;
  onUpdateLoadout?: (loadout: any, levels: any) => void;
  onEnvironmentOverrideChange?: (overrides: EnvironmentOverride, weather: WeatherType) => void;
  onInteractionStateChange?: (type: string | null) => void;
  isMobileDevice?: boolean;
  disableInput?: boolean;
  isWarmup?: boolean;
  currentSectorData?: any;
}
