import { SectorSystem } from './SectorSystem';
import { CinematicSystem } from './CinematicSystem';
import { HudSystem } from './HudSystem';
import { PerformanceMonitor } from './PerformanceMonitor';
import { AssetPreloader } from './AssetPreloader';
import { EnvironmentManager } from './EnvironmentManager';
import { SkySystem } from './SkySystem';
import { WindSystem } from './WindSystem';
import { WeatherSystem } from './WeatherSystem';
import { FogSystem } from './FogSystem';
import { WaterSystem } from './WaterSystem';
import { GroundSystem } from './GroundSystem';
import { LightSystem } from './LightSystem';
import { CameraSystem } from './CameraSystem';
import { InputManager } from '../core/engine/InputManager';
import { NavigationSystem } from './NavigationSystem';
import { OcclusionSystem } from './OcclusionSystem';
import { TriggerSystem } from './TriggerSystem';
import { LootSystem } from './LootSystem';
import { FXSystem } from './FXSystem';
import { FootprintSystem } from './FootprintSystem';
import { PlayerStatsSystem } from './PlayerStatsSystem';
import { PlayerMovementSystem } from './PlayerMovementSystem';
import { PlayerCombatSystem } from './PlayerCombatSystem';
import { PlayerManager } from './PlayerManager';
import { InteractionSystem } from './InteractionSystem';
import { PerkSystem } from './PerkSystem';
import { FamilySystem } from './FamilySystem';
import { VehicleManager } from './VehicleManager';
import { VehicleMovementSystem } from './VehicleMovementSystem';
import { ProjectileSystem } from './ProjectileSystem';
import { DamageNumberSystem } from './DamageNumberSystem';
import { CareerStatsSystem } from './CareerStatsSystem';
import { EnemyDetectionSystem } from './EnemyDetectionSystem';
import { DiscoverySystem } from './DiscoverySystem';
import { EnemySystem } from './EnemySystem';
import { EnemyWaveSystem } from './EnemyWaveSystem';
import { DeathSystem } from './DeathSystem';
import { CampEffectsSystem, CampFamilyAnimationSystem, CampChatterSystem } from '../components/camp/CampSystems';

export class SystemRegistry {
    public sector: SectorSystem | null = null;
    public cinematic: CinematicSystem | null = null;
    public hud: typeof HudSystem | null = null;
    public performanceMonitor: PerformanceMonitor | null = null;
    public assetPreloader: typeof AssetPreloader | null = null;
    public environment: EnvironmentManager | null = null;
    public sky: SkySystem | null = null;
    public wind: WindSystem | null = null;
    public weather: WeatherSystem | null = null;
    public fog: FogSystem | null = null;
    public water: WaterSystem | null = null;
    public ground: GroundSystem | null = null;
    public light: LightSystem | null = null;
    public camera: CameraSystem | null = null;
    public input: InputManager | null = null;
    public spatialGrid: any = null;
    public worldStreamer: any = null;
    public navigation: typeof NavigationSystem | null = null;
    public occlusion: OcclusionSystem | null = null;
    public triggerHandler: any = null;
    public triggerSystem: TriggerSystem | null = null;
    public loot: LootSystem | null = null;
    public fx: typeof FXSystem | null = null;
    public particle: any = null;
    public footprint: typeof FootprintSystem | null = null;
    public playerStats: PlayerStatsSystem | null = null;
    public playerMovement: PlayerMovementSystem | null = null;
    public playerCombat: PlayerCombatSystem | null = null;
    public interaction: InteractionSystem | null = null;
    public perkSystem: PerkSystem | null = null;
    public family: FamilySystem | null = null;
    public vehicleManager: typeof VehicleManager | null = null;
    public vehicleMovement: VehicleMovementSystem | null = null;
    public weaponHandler: any = null;
    public projectile: ProjectileSystem | null = null;
    public challengeTracker: any = null;
    public damageNumber: DamageNumberSystem | null = null;
    public careerStats: CareerStatsSystem | null = null;
    public enemyManager: any = null;
    public enemySystem: EnemySystem | null = null;
    public enemyAI: any = null;
    public enemyDetection: EnemyDetectionSystem | null = null;
    public enemyWave: EnemyWaveSystem | null = null;
    public death: DeathSystem | null = null;
    public campEffects: CampEffectsSystem | null = null;
    public campChatter: CampChatterSystem | null = null;
    public campFamilyAnimation: CampFamilyAnimationSystem | null = null;
    public discovery: DiscoverySystem | null = null;
    public playerManager: PlayerManager | null = null;
}