import * as THREE from 'three';
import { WeaponType, SectorTrigger, SectorState } from '../types';
import { Obstacle } from '../utils/physics';
import { Enemy } from './EnemyManager';
import { ScrapItem } from './systems/WorldLootSystem';
import { SpatialGrid } from './world/SpatialGrid';

export interface RuntimeState {
    isDead: boolean;
    score: number;
    collectedScrap: number;
    hp: number;
    maxHp: number;
    stamina: number;
    maxStamina: number;
    level: number;
    currentXp: number;
    nextLevelXp: number;
    activeWeapon: WeaponType;
    loadout: { primary: WeaponType; secondary: WeaponType; throwable: WeaponType; };
    weaponLevels: Record<WeaponType, number>;
    weaponAmmo: Record<WeaponType, number>;
    isReloading: boolean;
    reloadEndTime: number;
    rollStartTime: number;
    rollDir: THREE.Vector3;
    isRolling: boolean;
    invulnerableUntil: number;
    spacePressTime: number;
    spaceDepressed: boolean;
    eDepressed: boolean;
    isRushing: boolean;
    rushCostPaid: boolean;
    wasFiring: boolean;
    throwChargeStart: number;
    enemies: Enemy[];
    particles: any[];
    activeEffects: any[]; // Objects with persistent effects (fire, smoke)
    projectiles: any[];
    fireZones: any[];
    scrapItems: ScrapItem[];
    chests: any[];
    cameraShake: number;
    lastHudUpdate: number;
    startTime: number;
    lastShotTime: number;
    shotsFired: number;
    shotsHit: number;
    throwablesThrown: number;
    damageDealt: number;
    damageTaken: number;
    bossDamageDealt: number;
    bossDamageTaken: number;
    killsByType: Record<string, number>;
    seenEnemies: string[]; // New
    seenBosses: string[]; // New
    visitedPOIs: string[]; // New
    bossesDefeated: number[]; // New: Map IDs of bosses killed this run
    familyFound: boolean;
    familyExtracted: boolean;
    chestsOpened: number;
    bigChestsOpened: number;
    killsInRun: number;
    isInteractionOpen: boolean;
    bossSpawned: boolean;
    bloodDecals: any[];
    lastDamageTime: number;
    lastStaminaUseTime: number;
    noiseLevel: number;
    speakBounce: number;
    hurtShake: number;
    shakeIntensity: number;
    sectorState: SectorState;
    triggers: SectorTrigger[];
    obstacles: Obstacle[];
    collisionGrid: SpatialGrid;
    busUnlocked: boolean;
    clueActive: boolean;
    bossDefeatedTime: number;
    lastActionTime: number;
    thinkingUntil: number;
    speakingUntil: number;
    deathStartTime: number;
    killerType: string;
    killerName: string;
    playerBloodSpawned: boolean;
    deathVel: THREE.Vector3;
    lastTrailPos: THREE.Vector3 | null;
    framesSinceHudUpdate: number;
    lastFpsUpdate: number;
    isMoving: boolean;
    interactionType: 'chest' | 'plant_explosive' | 'collectible' | 'knock_on_port' | null;
    interactionTargetPos: THREE.Vector3 | null;
    nearestCollectible?: SectorTrigger | null;
    onClueFound?: ((clue: SectorTrigger) => void) | null;
    onCollectibleFound?: ((id: string) => void) | null;
    gainXp?: ((amount: number) => void) | null;
    bossIntroActive: boolean;
    sessionCollectiblesFound: string[];
    collectiblesFound: string[];
    mapItems: any[];
}

