
import * as THREE from 'three';

export const MATERIALS = {
  bullet: new THREE.MeshBasicMaterial({ color: 0xffffaa }),
  grenade: new THREE.MeshStandardMaterial({ color: 0x3f663f, roughness: 0.6 }),
  molotov: new THREE.MeshStandardMaterial({ color: 0x8B4513, roughness: 0.3, emissive: 0x331100, emissiveIntensity: 0.2 }),
  blood: new THREE.MeshBasicMaterial({ color: 0xaa0000 }),
  gore: new THREE.MeshStandardMaterial({ color: 0x660000, roughness: 0.2 }),
  fire: new THREE.MeshBasicMaterial({ color: 0xff6600, transparent: true, opacity: 0.8 }),
  fireZone: new THREE.MeshBasicMaterial({ color: 0xff3300, transparent: true, opacity: 0.3, side: THREE.DoubleSide }),
  smoke: new THREE.MeshBasicMaterial({ color: 0x555555, transparent: true, opacity: 0.6 }),
  walker: new THREE.MeshStandardMaterial({ color: 0x5a6e5a, roughness: 0.5 }),
  runner: new THREE.MeshStandardMaterial({ color: 0x8f3a3a, roughness: 0.5 }),
  tank: new THREE.MeshStandardMaterial({ color: 0x2d3436, roughness: 0.5 }),
  bomber: new THREE.MeshStandardMaterial({ color: 0xcf6e36, roughness: 0.5 }),
  scrap: new THREE.MeshBasicMaterial({ color: 0xffaa00 }),
  stone: new THREE.MeshStandardMaterial({ color: 0x555555, roughness: 0.9 }),
  treeTrunk: new THREE.MeshStandardMaterial({ color: 0x3d342b, roughness: 1.0 }), // Dark rough bark
  treeLeaves: new THREE.MeshStandardMaterial({ color: 0xf0f8f0, roughness: 0.9, flatShading: true }), // Snowy foliage
  family: new THREE.MeshStandardMaterial({ color: 0x00aaff, roughness: 0.5 }),
  familyRing: new THREE.MeshBasicMaterial({ color: 0x00ff00, transparent: true, opacity: 0.5, side: THREE.DoubleSide }),
  familyArrow: new THREE.MeshBasicMaterial({ color: 0x00aaff, transparent: true, opacity: 0.8 }),
  trackerArrow: new THREE.MeshBasicMaterial({ color: 0x00ffff, transparent: true, opacity: 0.8, side: THREE.DoubleSide }),
  skin: new THREE.MeshStandardMaterial({ color: 0xffccaa }),
  gun: new THREE.MeshStandardMaterial({ color: 0x222222 }),
  chestStandard: new THREE.MeshStandardMaterial({ color: 0x5c4033 }),
  chestBig: new THREE.MeshStandardMaterial({ color: 0xffd700 }),
  blastRadius: new THREE.MeshBasicMaterial({ color: 0xff0000, transparent: true, opacity: 0.3, side: THREE.DoubleSide }),
  bloodDecal: new THREE.MeshBasicMaterial({ 
      color: 0x660000, 
      transparent: true, 
      opacity: 0.8, 
      side: THREE.DoubleSide, 
      depthWrite: false, 
      depthTest: true,   
      polygonOffset: true, 
      polygonOffsetFactor: -4 
  }),
  scorchDecal: new THREE.MeshBasicMaterial({ 
      color: 0x111111, 
      transparent: true, 
      opacity: 0.8, 
      side: THREE.DoubleSide, 
      depthWrite: false,
      depthTest: true,
      polygonOffset: true,
      polygonOffsetFactor: -3
  }),
  footprintDecal: new THREE.MeshBasicMaterial({ 
      color: 0xaa2222, 
      transparent: true, 
      opacity: 0.6, 
      side: THREE.DoubleSide, 
      depthWrite: false,
      depthTest: true,
      polygonOffset: true,
      polygonOffsetFactor: -2 
  }),
  fog: new THREE.MeshBasicMaterial({ color: 0x111116, transparent: true, opacity: 0.1, depthWrite: false }),
  building: new THREE.MeshStandardMaterial({ color: 0x2a2a2a, roughness: 0.8 }),
  concrete: new THREE.MeshStandardMaterial({ color: 0x444444, roughness: 0.9 }),
  pipe: new THREE.MeshStandardMaterial({ color: 0x8b4513, roughness: 0.6, metalness: 0.4 }),
  mast: new THREE.MeshStandardMaterial({ color: 0x8899aa, roughness: 0.4, metalness: 0.8, wireframe: true }),
  barrel: new THREE.MeshStandardMaterial({ color: 0x404040, roughness: 0.7 }),
  barrelExplosive: new THREE.MeshStandardMaterial({ color: 0xcc2222, roughness: 0.5 }),
  road: new THREE.MeshStandardMaterial({ color: 0x1a1a1a, roughness: 0.9 }),
  train: new THREE.MeshStandardMaterial({ color: 0xffaa00, roughness: 0.6, metalness: 0.3 }),
  steel: new THREE.MeshStandardMaterial({ color: 0x555555, roughness: 0.4, metalness: 0.8 }),
  redWood: new THREE.MeshStandardMaterial({ color: 0x8a2be2, roughness: 0.9 }),
  yellowBrick: new THREE.MeshStandardMaterial({ color: 0xd4c685, roughness: 0.95 }),
  brownBrick: new THREE.MeshStandardMaterial({ color: 0x5c4033, roughness: 0.95 }),
  glass: new THREE.MeshStandardMaterial({ color: 0x88ccff, roughness: 0.1, metalness: 0.9, transparent: true, opacity: 0.6 }),
  glassBroken: new THREE.MeshStandardMaterial({ color: 0x223344, roughness: 0.4, metalness: 0.5 }),
  snow: new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 1.0 }),
  asphalt: new THREE.MeshStandardMaterial({ color: 0x151515, roughness: 0.8 }),
  gravel: new THREE.MeshStandardMaterial({ color: 0x2a2a2a, roughness: 1.0 }),
  metalPanel: new THREE.MeshStandardMaterial({ color: 0x778899, roughness: 0.3, metalness: 0.7 }),
  neonSign: new THREE.MeshBasicMaterial({ color: 0xffffff }),
  blackMetal: new THREE.MeshStandardMaterial({ color: 0x050505, metalness: 0.6, roughness: 0.4 }),
  crossEmissive: new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 2.0 }),
  aimCross: new THREE.MeshBasicMaterial({ color: 0xffffff, side: THREE.DoubleSide }),
  aimReticle: new THREE.MeshBasicMaterial({ color: 0xff0000, side: THREE.DoubleSide, transparent: true, opacity: 0.8 }),
  landingMarker: new THREE.MeshBasicMaterial({ color: 0xff0000, transparent: true, opacity: 0.8, side: THREE.DoubleSide }),
  ash: new THREE.MeshStandardMaterial({ color: 0x111111, roughness: 1.0 }),
  flashWhite: new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.8, depthWrite: false }),
  glassShard: new THREE.MeshBasicMaterial({ color: 0xccffff, transparent: true, opacity: 0.6, side: THREE.DoubleSide }),
  shockwave: new THREE.MeshBasicMaterial({ color: 0xffaa00, transparent: true, opacity: 0.6, side: THREE.DoubleSide, blending: THREE.AdditiveBlending })
};
